apiVersion: v1
kind: Pod
metadata:
  name: sample
  namespace: default
spec:
  containers:
  - env:
    - name: whatever 
      value: "1"
    - name: MODEL_ID
      value: /repository
    - name: NEURON_PROCESS_TAG
      value: tag-raphael-gl-test4-81c8b
    image: whatever 
    imagePullPolicy: Always
    name: api
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        aws.amazon.com/neuron: "12"
        cpu: "190"
        ephemeral-storage: 1536G
        memory: 760G
      requests:
        aws.amazon.com/neuron: "12"
        cpu: "190"
        ephemeral-storage: 1536G
        memory: 760G
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /repository
      name: repository
    - mountPath: /dev/shm
      name: shm
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  initContainers:
  - args:
    - --repository_id
    - meta-llama/Meta-Llama-3-70B-Instruct
    - --revision
    - 359ec69a0f92259a3cd2da3bb01d31e16c260cfc
    - --framework
    - pytorch
    env:
    - name: MAX_TIME
      value: "600"
    - name: MAX_RETRIES
      value: "3"
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TQDM_POSITION
      value: "1"
    - name: TQDM_MININTERVAL
      value: "1"
    - name: HF_ENDPOINT
      value: https://huggingface.co
    - name: HUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: your-token
          optional: false
    image: raphael31415/repo-loader:sample
    imagePullPolicy: IfNotPresent
    name: repository-loader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /repository
      name: repository
  nodeSelector:
    node-group: aws-us-east-1-inferentia2-48xlarge
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: custom-neuron-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: aws.amazon.com/neuron
    operator: Exists
  volumes:
  - emptyDir: {}
    name: repository
