apiVersion: v1
kind: Pod
metadata:
  name: sample-raph
  namespace: default
spec:
  containers:
  - args:
    - --repository_id
    - meta-llama/Meta-Llama-3-70B-Instruct
    - --revision
    - 359ec69a0f92259a3cd2da3bb01d31e16c260cfc
    - --framework
    - pytorch
    resources:
      limits:
        cpu: "190"
      requests:
        cpu: "190"
    env:
    - name: MAX_TIME
      value: "600"
    - name: MAX_RETRIES
      value: "3"
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: TQDM_POSITION
      value: "1"
    - name: TQDM_MININTERVAL
      value: "1"
    - name: HF_ENDPOINT
      value: https://huggingface.co
    - name: HUB_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: your-secret
          optional: false
    image: raphael31415/repo-loader:sample
    imagePullPolicy: Always
    name: repository-loader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /repository
      name: repository
  nodeSelector:
    node-group: aws-us-east-1-inferentia2-48xlarge
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: custom-neuron-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  tolerations:
  - effect: NoSchedule
    key: aws.amazon.com/neuron
    operator: Exists
  volumes:
  - emptyDir: {}
    name: repository
